name: Next

on:
  workflow_call:
    input:
      text:
        type: string
        required: true

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: echo "${{ github.event.inputs.text }}"
