name: Next

on:
  workflow_call:
    inputs:
      text:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      text:
        type: string
        required: true

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: echo "${{ inputs.text }}"
