name: Reusable workflow example

on:
  workflow_call:

jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - name: output
        id: my
        run: echo "myValue=1" >> $GITHUB_OUTPUT
      - name: debug
        run: echo ${{ steps.my.myValue }}
