name: Reusable workflow example

on:
  workflow_call:
    outputs:
      test:
        value: ${{ jobs.example_job.outputs.test }}

jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    outputs:
      test: ${{ steps.my.outputs.test }}
    steps:
      - name: output
        id: my
        run: echo "test=hello" >> $GITHUB_OUTPUT
      - name: debug
        run: echo "${{ steps.my.outputs.test }}"
