name: Run

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  workflow_dispatch:

jobs:
  run:
    uses: muukii/play-github-actions/.github/workflows/Reusable.yml@main



          
