name: Run

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  workflow_dispatch:

jobs:
  run:
    runs-on: macos-12
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Build
        run: ruby -v
      - uses: muukii/play-github-actions/.github/workflows/Reusable.yml@main


          
